### PR TITLE
Pull request for GKE TF scripts

### PR DESCRIPTION
**Pull request by alfredtommy**
Hi Finos team,

Here is some code contribution to the gcp/gke module of clous-service-certification. 
It is a terraform script for the deployment of a secure GKE infrastructure environment on GCP.

Note: I will modify the README text doc to markdown format soon

### CODE REVIEW

**Comment by mcleo-d** [comment]
Hey @alfredtommy

Thanks for contributing this pull request 🚀🚀🚀  

I have added this PR to the agenda for the next project meeting on 8th October #62 if you're able to attend and introduce to the group?

Speak soon,

James.

**Comment by mcleo-d** [comment]
Hi @leefaus

@alfredtommy has now contributed the first Terraform PR for GCP GKE 😁 

Is there scope to use this PR to experiment with #62 and the use of Pulumi?

Maybe have an offline chat with @alfredtommy and bring your thoughts to the next CSC meeting on 8th October #75 ..?

James.

**Comment by mcleo-d** [comment]
A code review of **Pull request for GKE TF scripts** #73 occurred on Wednesday 4th November @ 2pm GMT / 12 noon ET.

| Attendee | GitHub Profile | Firm |
|:-----|:-----|:-----|
| Alfred Tommy | @alfredtommy | Searce |
| Abdullah Garcia | @abdullahgarcia | JPMC | 
| James McLeod | @mcleo-d  | FINOS |

**Review by peterrhysthomas — APPROVED** [review]
Looks good to me, big thanks to @alfredtommy for all the hard work

**Pull request merged**
