### PR TITLE
Add kanban link to README.MD

### PR DESCRIPTION
**Pull request by mcleo-d**
Adds a Cloud Service Certification kanban link to the project README.MD

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Just wondering - any reason why that board isn't located [within the project?](https://github.com/finos/cloud-service-certification/projects) - it would be mreo discoverabl

**Comment by mcleo-d** [comment]
Hi @ColinEberhardt - I noticed you accepted the PR and then reopened. Please feel free to let me know your reasons as would like to know the community is confident with the change.

Kind regards,

James.

**Comment by ColinEberhardt** [comment]
>  Please feel free to let me know your reasons

Simple - I clicked the wrong button by mistake! Hence I re-opened immediately afterwards 🙄

**Comment by mcleo-d** [comment]
Thanks for your feedback @ColinEberhardt. I'm so happy you didn't have second thoughts 😄

**Pull request merged**
