### PR TITLE
Updating template table to include new categories and extra detail

### PR DESCRIPTION
**Pull request by danizheleva**
As discussed in our previous meeting, I am updating the table in the template to include more detail and a breakdown of categories. I have also removed the RedShift specific examples and added prompts as to the information that should be included in each section - please feel free to amend these/add extra detail to help users understand and use the template.

### CODE REVIEW

**Comment by mcleo-d** [comment]
Hi @danizheleva - Thanks for raising the PR 👍 I have assigned the item to you, have linked to the issue and have requested a review by @git-hub-forwork1 😄 

cc @peterrhysthomas

**Comment by mcleo-d** [comment]
I am also cc'ing @alfredtommy 👍

**Comment by mcleo-d** [comment]
@danizheleva and @peterrhysthomas - Thanks for your time contributing this pull request. 

@git-hub-forwork1 - If you can complete the final review and merge the PR if appropriate that would be awesome! 😸 

Speak soon,

James.

**Comment by mcleo-d** [comment]
Congrats on the pull request @danizheleva , @peterrhysthomas and @git-hub-forwork1 🎉🎉🎉 

Awesome teamwork! 👏 💯💯💯

**Comment by brooklynrob** [comment]
Great stuff.

**Pull request merged**
