### PR TITLE
EKS - Terraform

### PR DESCRIPTION
**Pull request by abdullahgarcia**
The following files have been reviewed, but there are several files still pending to be added as I'm currently reviewing them.

### CODE REVIEW

**Comment by mcleo-d** [comment]
Please say hello here if you would like to review 👋

**Comment by abdullahgarcia** [comment]
> Please say hello here if you would like to review 👋

James, do we know who volunteered for reviewing the pull request? That way we can add that person to the reviewers list.

**Comment by mcleo-d** [comment]
Hi @njwilliams 👋  

I'm unable to add you to the reviewers list, but it would be great if you could review this PR as discussed in #114 for @abdullahgarcia so we can accept and potentially merge in [Sprint 2](https://github.com/orgs/finos/projects/1#column-13982219).

I have also asked the CSC community for help in the FINOS CSC Slack - https://finos-lf.slack.com/archives/C01RNUMC2DP/p1619609764075100

Thanks for your help.

James 🚀

**Review by peterrhysthomas — COMMENTED** [review]
This looks good to me, it would be good to get a comparison of this versus the GKE for Azure and GCP so if @TLATER or @alfredtommy to see if there is anything they think of note - @mcleo-d will create a new issue  for enhancements to this which can be used for anything we would like to add afterwards.

**Comment by mcleo-d** [comment]
@abdullahgarcia and @peterrhysthomas,

Issue #123 has been raised to carry this contribution forward with the CSC and wider OSS community. 

Congratulations once again!

James 🚀

**Pull request merged**
