### PR TITLE
Service Accelerator Template for EKS (Kubernetes) on Amazon AWS

### LINKED ISSUE #66: AWS EKS definition
## Work Items
- [x] Service Accelerator Template for EKS (Kubernetes) on Amazon AWS #76
- [ ] Create scripts for deployment of EKE cluster as defined in Service Approval Accelerator template #113 
- [ ] Testing and validation of above mentioned scripts
- [ ] Raise PR request accordingly

### PR DESCRIPTION
**Pull request by abdullahgarcia**
This is the Service Accelerator Template completed for EKS (Kubernetes) on Amazon AWS.

Closes #66

### CODE REVIEW

**Comment by mcleo-d** [comment]
This item is **Ready for Review** by the Cloud Service Certification and wider open source community 🚀

**Comment by mcleo-d** [comment]
A code review of this pull request is confirmed for **Monday 30th November @11am ET / 4pm GMT** on the [FINOS Community WebEx](https://finos.webex.com/meet/community).

During the call, we'll also compare to the **CDMC Capability Structure** to understand synergies and gaps.

**Comment by peterrhysthomas** [comment]
It would be good to be more opinionated on some of the options where they would be expected by an organisations CSO, such as the encryption of secrets.  Other than that this looks really good.

**Comment by abdullahgarcia** [comment]
> It would be good to be more opinionated on some of the options where they would be expected by an organisations CSO, such as the encryption of secrets. Other than that this looks really good.

@peterrhysthomas , I've updated the document accordingly. Thanks for the feedback!

**Pull request merged**
