### PR TITLE
AWS EKS Review, Feedback and Update

### PR DESCRIPTION
**Pull request by abdullahgarcia**
- Declare and set variables to handle worker groups details.
- Document the supported versions in the Terraform modules.

### CODE REVIEW

**Comment by cphang99** [comment]
The stems from a discussion covered in https://github.com/finos/cloud-service-certification/commit/9e9ec68bc8242b69152cf2258c401fcd5b738f32#r55422977 where we agreed that adding variables to configure the worker groups more flexibly would be beneficial.

In addition, deployment of EKS clusters can be sensitive to the [terraform-eks-module version](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest) being employed, documentation has been added so users know what is currently supported.

I'm happy with everything contained here, however, I think there's one minor thing that has been missed to support the second point, I will add an inline comment.

**Comment by cphang99** [comment]
the `eks` module can be further configured so that `version` is set in the module declaration. In my experience this can be important as not all eks versions are fully supported with all terraform eks modules.

From: https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "17.20.0"
  # insert the 7 required variables here
}
```

**Comment by mcleo-d** [comment]
CSC project reviewed during #140 and @abdullahgarcia to clarify last comment with @cphang99

**Comment by mcleo-d** [comment]
Hi @abdullahgarcia 

The Linux Foundation EasyCLA team has solved the blocking CLA check and you're now free to merge this PR with @cphang99's feedback.

All the best,

James.

**Pull request merged**
