### PR TITLE
Service Approval Accelerator for GKE service in GCP

### PR DESCRIPTION
**Pull request by alfredtommy**
Service Approval Accelerator Template for GKE is still a work in progress but I would like to create a PR to enable collaboration and feedback on whatever has been submitted so far

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Alfred Tommy

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by mcleo-d** [comment]
Thank you for your pull request @alfredtommy and @pudern 👏 💯💯💯 

I'll ask @peterrhysthomas and @git-hub-forwork1 to inform the CSC community you're happy for them review and feedback on the work being done 🤜 💥 🚀

**Comment by mindthegab** [comment]
This is amazing stuff, looking forward to seeing this project take off! 🚀

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Alfred Tommy

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by mcleo-d** [comment]
Comments and Feedback from PR review call on **Wednesday 22nd July @ 2pm BST / 9am ET** with @alfredtommy below ...

### Pull Request Review Attendees
| Attendee | Firm | GitHub ID |
|:--- |:--- |:--- |
James McLeod | FINOS | @mcleo-d |
Alfred Tommy | Searce | @alfredtommy |
Abdullah Garcia | JPMC | @abdullahgarcia |
Daniele Zheleva | Deutsche Bank | @danizheleva |
Davide Martorana | Deutsche Bank | |
Freddie Leadsom | Deutsche Bank | @fleadsom |
Max | Deutsche Bank | |
Peter Thomas | Deutsche Bank | @peterrhysthomas |

**Comment by alfredtommy** [comment]
Feedback from 22nd July session:

1) Add note for gke ingress (encryption of data in transit) regarding open source options istio/nginx 
2) Add similar note for isolation (eg: pod isolation network policy options)
2) Add cloud HSM to encryption kms since it is in GA now
3) Isolation: how to isolate applications -> between nodepools? between clusters? and how to address data segregation

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Alfred Tommy

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Alfred Tommy

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Alfred Tommy

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by alfredtommy** [comment]
Updates to the template master:

1) Added note regarding 3rd party/open-source tools in the encryption in transit category in the context of gke lb vs istio/nginx
2) Added Cloud HSM to the encryption management category
3) Added several points on how to achieve isolation on GKE in the isolation category

**Comment by peterrhysthomas** [comment]
This is great, I am very happy to approve this request. There is outstanding work but it is better to merge this as a work in progress so we can collaborate on the next steps.

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Alfred Tommy

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Alfred Tommy

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Alfred Tommy

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Alfred Tommy

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Alfred Tommy

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Alfred Tommy

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Alfred Tommy

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Alfred Tommy

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Pull request merged**
